travis:
  secure:
    BINSTAR_TOKEN: Ad3pbxdfqUuU5AZzZjD9ubC1Yh+Xl1z2XHyJiqqG7KK0f6VZaa+JE8Xdzh3bEb5bZaPmlkUDY94FK1TO/IwS1WtRA4bVvSB52Z1J4AE0KXWjgBdt64hKn2Im+Rc1lFj1eaBtKF/B736XhWUZRqm/ZUn0f5UI4vXI5NSMe9jpd3aXOwdmnpVLIQsJF7/F81CeHLP1J6GHRy41Jq4dJ6bD0lSBcuTSB/VkdCHUV4VWo/B2zGjgXD14KQ3ixOxyE+j+eKlfXcihxayiS6BadpXL+DL8Im4GrFnXrov42Cjtram7RcGdrfcdcQUcS0gSQ/Qu09LwGNxejsS5JFy6LcMGFGNuYR00E1MDF1eiCfDW/iVGb0vHcm5kJcTWpDAMHWxaE4bqy4ZKjLSVZAcwdF7mFQT7NJ5HNIOkzYM/rIdpJ9ap0Ve0y6suw+WoncdUiwElClntZ4Ngm2Wud4IpXH5DWs1/lJANTRaESu1ObqFhELEN9+3Ie7ocjtLUzVWATPlEMM7fY+MhIsi58Cxswx8KgnxXwZ9G3kPJWASoEvNdMeNhi8tkVcqsVt//PYJ7KDPjd1QkHLiV9MPiz/KBCE2cd85bonNoqTrovCDRlouHlub+dMHHlE6LCAdb0xt+qMCQxpeZaAiI9+nkBfV9WCAw8nSahuF3YKsZaqvpCN9Ng1s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
